<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Models_Backup\**" />
    <EmbeddedResource Remove="Data\Models_Backup\**" />
    <None Remove="Data\Models_Backup\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Identity\Data\Migrations\00000000000000_CreateIdentitySchema.cs" />
    <Compile Remove="Identity\Data\Migrations\00000000000000_CreateIdentitySchema.Designer.cs" />
    <Compile Remove="Identity\Data\Migrations\20250816074902_application.cs" />
    <Compile Remove="Identity\Data\Migrations\20250816074902_application.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Core" Version="2.3.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Booking.Application\Booking.Application.csproj" />
    <ProjectReference Include="..\Booking.Domain\Booking.Domain.csproj" />
    <ProjectReference Include="..\TemplateBinder\TemplateBinder.csproj" />
  </ItemGroup>

</Project>
